@baseUrl = http://localhost:3001/api
@username = testuser1@example.com

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "{{username}}",
  "name": "Test User",
  "password": "secret"
}

GET {{baseUrl}}/users

PUT {{baseUrl}}/users/{{username}}
Content-Type: application/json

{
  "name": "Updated Test User"
}

GET {{baseUrl}}/users

# @name createBlog
POST {{baseUrl}}/blogs
Content-Type: application/json

{
  "title": "Blog owned by user",
  "author": "Autor",
  "url": "https://example.com/blog-owned-by-user",
  "likes": 3,
  "userId": {{createUser.response.body.$.id}}
}

GET {{baseUrl}}/blogs